version: '2.1'

services:
  rabbitmq:
    image: datafyit/rabbitmq:shovel
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=password
    expose:
      - "5672"
      - "15672"