server:
  port: 8761

info:
  component: Discovery Server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0
    numberRegistrySyncRetries: 0
    response-cache-update-interval-ms: 1000
  password: ${SECURITY_USER_PASSWORD:password}

logging:
  level:
    root: INFO
    org.springframework: WARN

spring:
  application:
    name: "@project.artifactId@"
  devtools:
    livereload:
      enabled: false
---
# Eureka instance 1 when used on Docker
spring:
  profiles: docker
eureka:
  instance:
    hostname: discovery