info:
  component: "@project.name@"
  name: "@project.artifactId@"
  versiom: "@project.version@"

server:
  port: 8888

spring:
  application:
    name: "@project.artifactId@"
  devtools:
    livereload:
      enabled: false
  cloud:
    config:
      server:
        git:
          uri: file:///${PWD}/poc-ground-config/

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework: WARN
---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: file:///config-repo
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/